### PR TITLE
Add Prettier and refactor ESLint configuration

### LINKED ISSUE #82: Use Code Formatter and Linter
While the project does have a lint config and lint scripts, barely anyone uses it and the code could use some nice formatting as well.

### PR DESCRIPTION
**Pull request by timoschwarzer**
- Adds Prettier
- Refactor ESLint config
- Run lint and build on push and PRs

Usage: `npm run lint` (`npm run lint -- --fix` to fix).

All files have been reformatted to match the Prettier rules.

Closes #82

### CODE REVIEW

**Comment by lepelog** [comment]
I'm not sure if this is a good idea, we need to coordinate that internally since we sometimes share code with our restream layouts, and it would suck if cherry picking stops working because of this.

Also, the `schema/*.d.ts` files are autogenerated and should not be formatted

Not sure if adding github actions is useful, since we always push to master anyways, seems like a waste of resources

**Comment by timoschwarzer** [comment]
> Not sure if adding github actions is useful, since we always push to master anyways, seems like a waste of resources

For ori-rando CI pipelines were very useful to detect errors early, especially ones that occurr because of missing/uncommitted files or similar since it always does a clean build in CI.

**Comment by timoschwarzer** [comment]
> Also, the `schema/*.d.ts` files are autogenerated and should not be formatted

https://github.com/bingothon/bingothon-layouts/pull/86/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R38

They aren't formatted.

**Comment by timoschwarzer** [comment]
I'll take a look at it, can't promise it'll be before next year though 😅

**Comment by Floha258** [comment]
@timoschwarzer Would you have time soon to look into this? Cause none of us, was able to really work it out

**Pull request merged**
